global using CsabaDu.FooVar.Common.Statics;
global using CsabaDu.FooVar.Geometrics.Statics;
global using CsabaDu.FooVar.Measures.Interfaces.DataTypes;
global using CsabaDu.FooVar.Measures.Interfaces.DataTypes.MeasureTypes;
global using CsabaDu.FooVar.Measures.Statics;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVar.Geometrics.Statics.CalculateGeometrics;
global using static CsabaDu.FooVar.Geometrics.Statics.ShapeTraits;
global using static CsabaDu.FooVar.Geometrics.Statics.ValidateGeometrics;
global using static CsabaDu.FooVar.Measures.Statics.MeasureUnit;
